apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-app
  namespace: cv
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv-app
  template:
    metadata:
      labels:
        app: cv-app
    spec:
      # imagePullSecrets:  # Not needed (EKS worker has role for ECR-access)
      # - name: cred
      containers:
      - name: cv-app-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8501