apiVersion: v1
kind: Service
metadata:
  name: fgpt-app-service
  namespace: fgpt
spec:
  type: NodePort
  selector:
    app: fgpt-app
  ports:
  - nodePort: 30082  # Port on which the node is accessible after deplyoment
    port: 5000
    targetPort: 5000