---
- hosts: build-server
  become: true
  tasks:
  - name: Update Ubuntu repo and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Add Deadsnakes PPA for Python 3.9
    apt_repository:
      repo: ppa:deadsnakes/ppa
      state: present

  - name: Install Python 3.9 related programs
    apt:
      name:
        - python3.9
        - python3.9-distutils
        - python3-pip
        - python3.9-venv
      state: present

  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Start Docker service
    service:
      name: docker
      state: started

  - name: Add user to Docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  - name: Ensure Docker starts at boot time
    service:
      name: docker
      enabled: yes

  - name: Verify Docker group membership
    command: groups "{{ ansible_user }}"
    register: group_result

  - name: Show group membership
    debug:
      var: group_result.stdout

  # Install Java
  - name: Install Java 17
    apt:
      name: openjdk-17-jdk
      state: present

  - name: Set JAVA_HOME in .bashrc
    lineinfile:
      path: '/home/{{ ansible_user }}/.bashrc'
      line: 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'      
      state: present

  - name: Add Java to PATH in .bashrc
    lineinfile:
      path: '/home/{{ ansible_user }}/.bashrc'
      line: 'export PATH="$PATH:/usr/lib/jvm/java-17-openjdk-amd64"'      
      state: present

  - name: Source .bashrc to reload environment variables
    shell: 'source /home/{{ ansible_user }}/.bashrc'    
    args:
      executable: /bin/bash

  - name: Verify Java installation
    command: java -version
    register: java_version_result

  - name: Show Java version
    debug:
      var: java_version_result.stdout

  - name: Install unzip (reqired for awscli2 install)
    apt:
      name: unzip
      state: present

  - name: Download AWS CLI v2
    get_url:
      url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
      dest: "/home/{{ ansible_user }}/awscliv2.zip"

  - name: Unzip AWS CLI v2
    unarchive:
      src: "/home/{{ ansible_user }}/awscliv2.zip"
      dest: "/home/{{ ansible_user }}/"
      remote_src: yes

  - name: Install AWS CLI v2
    command: "/home/{{ ansible_user }}/aws/install --update"

  - name: Verify awscli2 installation
    command: aws --version
    register: awscli_version_result

  - name: Show awscli2 version
    debug:
      var: awscli_version_result.stdout

  - name: Download kubectl
    get_url:
      url: "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"
      dest: "/home/{{ ansible_user }}/kubectl"
  
  - name: Make kubectl executable
    command: chmod +x "/home/{{ ansible_user }}/kubectl"

  - name: Move kubectl to /usr/local/bin
    command: mv "/home/{{ ansible_user }}/kubectl" /usr/local/bin/kubectl

  - name: Download Helm
    get_url:
      url: "https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3"
      dest: "/home/{{ ansible_user }}/get_helm.sh"
      mode: '0755'

  - name: Install Helm
    command: "/home/{{ ansible_user }}/get_helm.sh"

  - name: Verify Helm installation
    command: helm version
    register: helm_version_result

  - name: Show Helm version
    debug:
      var: helm_version_result.stdout

  - name: Add stable Helm repo
    command: helm repo add stable https://charts.helm.sh/stable
  
  - name: Update Helm repos (stable)
    command: helm repo update