---
- hosts: build-server
  become: true
  tasks:
  - name: Update Ubuntu repo and cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Add Deadsnakes PPA for Python 3.9
    apt_repository:
      repo: ppa:deadsnakes/ppa
      state: present

  - name: Install Python 3.9 related programs
    apt:
      name:
        - python3.9
        - python3.9-distutils
        - python3-pip
        - python3.9-venv
      state: present

  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Start Docker service
    service:
      name: docker
      state: started

  - name: Add user to Docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes

  - name: Ensure Docker starts at boot time
    service:
      name: docker
      enabled: yes

  - name: Verify Docker group membership
    command: groups "{{ ansible_user }}"
    register: group_result

  - name: Show group membership
    debug:
      var: group_result.stdout

  # Install Java
  - name: Install Java 11
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Set JAVA_HOME in .bashrc
    lineinfile:
      path: '/home/{{ ansible_user }}/.bashrc'
      line: 'export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
      state: present

  - name: Add Java to PATH in .bashrc
    lineinfile:
      path: '/home/{{ ansible_user }}/.bashrc'
      line: 'export PATH="$PATH:/usr/lib/jvm/java-11-openjdk-amd64"'
      state: present

  - name: Source .bashrc to reload environment variables
    shell: 'source /home/{{ ansible_user }}/.bashrc'
    args:
      executable: /bin/bash

  - name: Verify Java installation
    command: java -version
    register: java_version_result

  - name: Show Java version
    debug:
      var: java_version_result.stdout